# 常用属性

In [77]:
import numpy as np  # 就是一个类(属性+方法)
arr = np.arange(1,6,2)
print(arr.dtype,arr.shape)

int32 (3,)


# 创建

In [1]:
import numpy as np

In [4]:
arr = np.arange(1,6,2)
print(arr)

[1 3 5]


In [34]:
arr = np.array([i for i in range(10)])
print(arr)

arr = np.array([i for i in range(10)], dtype = np.float64)
print(arr.dtype)
arr_int = arr.astype(np.int64)
print(arr_int.dtype)

[0 1 2 3 4 5 6 7 8 9]
float64
int64


In [11]:
arr_zeros = np.zeros(10)
print(arr_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [13]:
arr_zeros = np.zeros((10, 3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [15]:
arr_ones = np.ones(10)
print(arr_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [18]:
arr_ones = np.ones((10,3))
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [25]:
from io import StringIO
c = StringIO(u"0 1\n2 3")

In [26]:
arr = np.loadtxt(c)
print(arr)

[[0. 1.]
 [2. 3.]]


In [30]:
d = StringIO(u"M 21 72\nF 35 58")

In [32]:
np.loadtxt(d, dtype={'names': ('gender', 'age', 'weight'), 'formats': ('S1', 'i4', 'f4')})

E:\Users\23230\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: loadtxt: Empty input file: "<_io.StringIO object at 0x0000015AFC0D5678>"
  """Entry point for launching an IPython kernel.


array([], dtype=[('gender', 'S1'), ('age', '<i4'), ('weight', '<f4')])

def loadtxt(fname, dtype=float, comments='#', delimiter=None,
            converters=None, skiprows=0, usecols=None, unpack=False,
            ndmin=0, encoding='bytes', max_rows=None):
            
def savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='',
            footer='', comments='# ', encoding=None):

# 索引

In [37]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [40]:
print(arr2d[0:1])

[[1 2 3]]


In [42]:
print(arr2d[0:0])

[]


In [44]:
print(arr2d[0])

[1 2 3]


In [46]:
print(arr2d[0,0])
print(arr2d[0:,0])
print(arr2d[0:,0:1])

1
[1 4 7]
[[1]
 [4]
 [7]]


In [48]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names, data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe'] [[ 1.03144465  0.23018199 -0.12209179  0.80929859]
 [ 1.39730813  1.3440795   0.90989593  1.21201314]
 [-0.1783057  -0.80969951  1.22759021 -1.31309432]
 [-0.06450213  1.03156141 -0.08505029 -0.36051046]
 [ 0.30244754  1.25462549  0.03078738  0.55792527]
 [ 0.49746762  1.1159134   0.6179331  -1.04476009]
 [ 0.21433494 -0.74213024 -1.05711487 -0.20710818]]


In [52]:
print(data[names=='Bob'])
print(data[names=='Bob',2:])

[[ 1.03144465  0.23018199 -0.12209179  0.80929859]
 [-0.06450213  1.03156141 -0.08505029 -0.36051046]]
[[-0.12209179  0.80929859]
 [-0.08505029 -0.36051046]]


# 运算

In [76]:
arr = np.random.randn(6, 3)
print(arr)
print(np.dot(arr.T, arr))
print(np.multiply(arr, arr))
print(np.isnan(arr))

[[-0.46815198  0.18167686 -0.17875988]
 [ 1.14090975 -1.09836961 -0.31992892]
 [-0.44751152 -0.17224383 -1.40622427]
 [-0.04593829 -1.41532463 -0.18617265]
 [-0.87529698 -0.15971517  0.79602598]
 [-1.50116676  0.38175534 -0.42140112]]
[[ 4.74286467 -1.62937451  0.292365  ]
 [-1.62937451  3.4434801   0.53662231]
 [ 0.292365    0.53662231  2.95767282]]
[[2.19166273e-01 3.30064798e-02 3.19550933e-02]
 [1.30167507e+00 1.20641580e+00 1.02354517e-01]
 [2.00266564e-01 2.96679369e-02 1.97746669e+00]
 [2.11032610e-03 2.00314381e+00 3.46602545e-02]
 [7.66144799e-01 2.55089357e-02 6.33657358e-01]
 [2.25350164e+00 1.45737138e-01 1.77578903e-01]]
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]


#  广播


# 改

In [58]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [61]:
result = np.where(xarr>1.2, xarr, yarr) # 相对于if-else
print(result)

[2.1 2.2 1.3 1.4 1.5]


# 统计函数

In [63]:
arr = np.random.randn(5, 4)
print(arr)

[[ 0.85100385 -0.95188168  1.6463485   0.47556421]
 [ 0.045704   -0.96752966 -0.52507537  2.26087031]
 [ 1.4985891  -1.64561377  0.14017907 -1.91341931]
 [ 0.44976634  1.53323283  0.84558711 -2.31429055]
 [ 2.17129942  0.15272675  1.08585943  0.33032776]]


In [65]:
print(arr.mean())
print(arr.mean(axis = 0))
print(arr.mean(axis = 1))

0.25846241615704696
[ 1.00327254 -0.37581311  0.63857975 -0.23218952]
[ 0.50525872  0.20349232 -0.48006623  0.12857393  0.93505334]


 sum; cumsum; std;var; min;max;

In [69]:
arr = np.random.randn(6)
print(arr)
arr.sort() # sort 
print(arr)

[ 0.42574545 -0.82354304 -1.9494687   1.96713727 -0.59470765  0.18628121]
[-1.9494687  -0.82354304 -0.59470765  0.18628121  0.42574545  1.96713727]


In [73]:
arr.sort(0) # 指定列排序
print(arr)

[-1.9494687  -0.82354304 -0.59470765  0.18628121  0.42574545  1.96713727]


In [75]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names) # 统计值

array(['Bob', 'Joe', 'Will'], dtype='<U4')

# 文件读写操作

np.save(filename, arr) # extension.npy
np.load() # 

# 线性代数内容

# 拼接
vstack((arr1, arr2))# 垂直
hstack((arr1, arr2)) # 水平